/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgaconnect;

import java.awt.Cursor;
import java.awt.Point;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.json.JSONObject;

/**
 *
 * @author josephs12
 */
public class ControlPanel extends javax.swing.JPanel {
    
    private static ControlPanel thisObj;
    
    /**
     * Creates new form PollMainScreen
     */
    public ControlPanel() {
        initComponents();
        thisObj = this;
    }
    
    public static ControlPanel getInstance() {
        return thisObj;
    }
    
    public void init() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        senators = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        removeSenator = new javax.swing.JButton();
        addSenator = new javax.swing.JButton();
        searchField = new javax.swing.JComboBox<>();
        search = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 251, 234));

        title.setFont(new java.awt.Font("Steelfish Outline", 1, 54)); // NOI18N
        title.setForeground(new java.awt.Color(163, 22, 33));
        title.setText("Control Panel");

        senators.setBackground(new java.awt.Color(221, 209, 199));
        senators.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        senators.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Senator Name", "Constituency"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        senators.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        senators.setFillsViewportHeight(true);
        senators.setSelectionBackground(new java.awt.Color(221, 209, 199));
        senators.setSelectionForeground(new java.awt.Color(0, 0, 0));
        senators.setShowVerticalLines(false);
        senators.getTableHeader().setReorderingAllowed(false);
        senators.setVerifyInputWhenFocusTarget(false);
        senators.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                senatorsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(senators);
        if (senators.getColumnModel().getColumnCount() > 0) {
            senators.getColumnModel().getColumn(0).setResizable(false);
            senators.getColumnModel().getColumn(0).setPreferredWidth(20);
        }
        senators.getAccessibleContext().setAccessibleName("Senators");

        backButton.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgaconnect/resources/Images/BackArrow.png"))); // NOI18N
        backButton.setMnemonic('c');
        backButton.setText("Back");
        backButton.setToolTipText("");
        backButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                backButtonMouseMoved(evt);
            }
        });
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        removeSenator.setText("-");

        addSenator.setText("+");

        searchField.setEditable(true);
        searchField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Senator Jake", "Senator Jojo", "Senator Jacklyn" }));
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgaconnect/resources/Images/magnifying_glass.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addSenator)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeSenator))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(title)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(removeSenator)
                        .addComponent(addSenator)))
                .addContainerGap())
        );

        removeSenator.getAccessibleContext().setAccessibleName("Delete Senator Button");
        addSenator.getAccessibleContext().setAccessibleName("Add Senator Button");
        searchField.getAccessibleContext().setAccessibleName("Search Field");
        search.getAccessibleContext().setAccessibleName("Search Icon");
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseMoved
        // TODO add your handling code here:
        //change to click mouse
        Cursor click = new Cursor(Cursor.HAND_CURSOR);
        backButton.setCursor(click);
    }//GEN-LAST:event_backButtonMouseMoved

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

    }//GEN-LAST:event_backButtonActionPerformed

    private void senatorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_senatorsMouseClicked

    }//GEN-LAST:event_senatorsMouseClicked

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSenator;
    private javax.swing.JButton backButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeSenator;
    private javax.swing.JButton search;
    private javax.swing.JComboBox<String> searchField;
    private javax.swing.JTable senators;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

}
