/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgaconnect;

import java.awt.Cursor;
import java.awt.Point;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josephs12
 */
public class ControlPanelSenatorAdd extends javax.swing.JPanel {
    
    private static ControlPanelSenatorAdd thisObj;
    
    /**
     * Creates new form PollMainScreen
     */
    public ControlPanelSenatorAdd() {
        initComponents();
        thisObj = this;
    }
    
    public static ControlPanelSenatorAdd getInstance() {
        return thisObj;
    }
    
    public void init() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        finish = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        senatorIcon = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        constituency = new javax.swing.JLabel();
        constituencyField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 251, 234));

        title.setFont(new java.awt.Font("Steelfish Outline", 1, 54)); // NOI18N
        title.setForeground(new java.awt.Color(163, 22, 33));
        title.setText("Add/Remove");

        finish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgaconnect/resources/Images/checkmark.png"))); // NOI18N

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgaconnect/resources/Images/x-mark.png"))); // NOI18N
        cancel.setToolTipText("");

        senatorIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgaconnect/resources/Images/profile-icon.png"))); // NOI18N

        name.setText("Name:");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        constituency.setText("Constituency:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(finish)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(368, 368, 368))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(senatorIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameField)
                                .addComponent(constituency)
                                .addComponent(constituencyField)))
                        .addGap(9, 9, 9))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(senatorIcon)
                        .addContainerGap(110, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(constituency)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(constituencyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(finish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())))))
        );

        title.getAccessibleContext().setAccessibleName("Add/Remove Title");
        finish.getAccessibleContext().setAccessibleName("Finish Button");
        cancel.getAccessibleContext().setAccessibleName("Cancel Button");
        senatorIcon.getAccessibleContext().setAccessibleName("Senator Profile Icon");
        name.getAccessibleContext().setAccessibleName("Name");
        nameField.getAccessibleContext().setAccessibleName("Name Field");
        constituency.getAccessibleContext().setAccessibleName("Constituency");
        constituencyField.getAccessibleContext().setAccessibleName("Constituency Field");
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JLabel constituency;
    private javax.swing.JTextField constituencyField;
    private javax.swing.JButton finish;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel senatorIcon;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

}
