/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgaconnect;

import java.awt.Cursor;
import java.awt.Point;
import java.awt.Window;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import sgaconnect.backend.MessageThread;
import sgaconnect.backend.User;

/**
 *
 * @author josephs12
 */
public class SenatorMessagesMain extends javax.swing.JPanel {

    private static SenatorMessagesMain thisObj;
    
    private MessageThread[] threads;
    
    /**
     * Creates new form PetitionMainScreen
     */
    public SenatorMessagesMain() {
        initComponents();
        thisObj = this;
    }
    
    public static SenatorMessagesMain getInstance() {
        return thisObj;
    }
    
    public void init() {
        User user = MainFrame.getBackend().getLoggedInUser();
        
        MessageThread[] threads = MainFrame.getBackend().getAllMessageThreads(user.getID());
        
        DefaultTableModel model = (DefaultTableModel) displayTable.getModel();
        model.setRowCount(threads.length);
        
        for (int i = 0; i < threads.length; i++) {
            
            Integer[] users = threads[i].getUsers().toArray(new Integer[0]);
            String usersString = "";
            
            for (int j = 0; j < users.length; j++) {
                usersString = usersString + MainFrame.getBackend().getUserByID(users[j]).getNetID();
                if (j != users.length-1) {
                    usersString = usersString + ", ";
                }
            }
            
            model.setValueAt(usersString, i, 0);
            model.setValueAt(threads[i].getSubject(), i, 1);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MessagesLabel = new javax.swing.JLabel();
        newButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 251, 234));

        MessagesLabel.setFont(new java.awt.Font("Steelfish Outline", 1, 54)); // NOI18N
        MessagesLabel.setForeground(new java.awt.Color(142, 15, 22));
        MessagesLabel.setText("Messages");

        newButton.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        newButton.setText("New");
        newButton.setMaximumSize(new java.awt.Dimension(125, 51));
        newButton.setPreferredSize(new java.awt.Dimension(125, 51));
        newButton.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                newButtonMouseMoved(evt);
            }
        });
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        displayTable.setBackground(new java.awt.Color(221, 209, 199));
        displayTable.setFont(new java.awt.Font("Open Sans", 0, 11)); // NOI18N
        displayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Student", "Subject"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        displayTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        displayTable.setFillsViewportHeight(true);
        displayTable.setInheritsPopupMenu(true);
        displayTable.setSelectionBackground(displayTable.getBackground());
        displayTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        displayTable.setShowVerticalLines(false);
        displayTable.getTableHeader().setReorderingAllowed(false);
        displayTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displayTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(displayTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MessagesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MessagesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        MainView.getInstance().changeView("senatorMessagesNew");
    }//GEN-LAST:event_newButtonActionPerformed

    private void newButtonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newButtonMouseMoved
        // TODO add your handling code here:
        //change to click mouse
        Cursor click = new Cursor(Cursor.HAND_CURSOR);
        newButton.setCursor(click);
    }//GEN-LAST:event_newButtonMouseMoved

    private void displayTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayTableMouseClicked
        try {
            JTable source = (JTable)evt.getSource();
            Point point = evt.getPoint();
            int row = source.rowAtPoint(point);
            System.out.println("Switching to thread " + row);
            SenatorMessagesView.getInstance().init(threads[row]);
            MainView.getInstance().changeView("senatorMessagesView");
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_displayTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MessagesLabel;
    private javax.swing.JTable displayTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newButton;
    // End of variables declaration//GEN-END:variables
}
